### PR TITLE
Create TSG for VCO creation issue

### PR DESCRIPTION
**Pull request by mamezgeb**

### CODE REVIEW

**Comment by mamezgeb** [comment]
Hi @sethmanheim, creating a TSG for the known-issues-installation area following the process you walked me through last month. Can you review?

**Comment by sethmanheim** [comment]
@mamezgeb Awesome, thank you! I will review ASAP.

**Comment by mamezgeb** [comment]
Thanks @sethmanheim, ready for immediate publication

**Comment by mamezgeb** [comment]
Fyi @SummerSmith for your tracking - adding an Install TSG

**Pull request merged**
